# -*- coding: utf-8 -*-
"""Traffic_Signs_Recognition_using_CNN_and_Keras_in_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pyC5sH_-OKVZKjkwL0FUTqOZVaZEL7hd

# **CNN model building**
I builded a multi-layer **feedforward** neural network to classify traffic sign images using Keras
"""

from keras.models import Sequential
from keras.layers import Conv2D, MaxPool2D, Dense, Activation, Flatten

# Create the Sequential model
model = Sequential()

#convolutional layer with 32 filters, a 3x3 kernel, and valid padding .
model.add(Conv2D(filters=32, kernel_size=(3,3), input_shape=(32, 32, 3),padding='VALID'))

#ReLU activation layer
model.add(Activation('relu'))

#2x2 max pooling layer
model.add(MaxPool2D(pool_size=(2, 2)))

#dropout layer with a rate of 50%
model.add(Dropout(rate=0.5))

#flatten layer with the input_shape set to (32, 32, 3)
model.add(Flatten(input_shape=(32, 32, 3)))

#fully connected layer with an output width of 128
model.add(Dense(128))

#ReLU activation function
model.add(Activation('relu'))

#fully connected layer with an output width of 5 
'''
because for this data set there are only 5 classes.

'''
model.add(Dense(5))

#softmax activation function
model.add(Activation('softmax'))